# Generated by Django 5.2.7 on 2025-12-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_rename_actors_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BR', 'Brasil'), ('UK', 'Reino Unido')], max_length=100, null=True),
        ),
    ]
